=pod

=encoding utf8

=head1 NAME

vcard2featurephone - Transform a vcard address book to be able to be imported in an old phone

=head1 SYNOPSIS

vcard2featurephone [options] MaxLengthOfNames

=head1 DESCRIPTION

Feature phones might have limitations in the length of names of contacts. This
script helps to transform a given vcard address book database to fit on such
feature phones.

For Example the following input vcard

    BEGIN:VCARD
    VERSION:3.0
    FN:Bertolt Testinger
    N:Testinger;Bertolt;;;
    EMAIL;TYPE=INTERNET:Bertolt.testinger@beispiel.at
    TEL;TYPE=CELL:+43 123 456 78 90
    TEL;TYPE=WORK:+43 90 87 654 32 1
    BDAY:1970-01-01
    END:VCARD

will be transformed to

    BEGIN:VCARD
    VERSION:3.0
    FN:Bertolt Testin(cell)
    TEL:+43 123 456 78 90
    END:VCARD
    BEGIN:VCARD
    VERSION:3.0
    FN:Bertolt Testin(work)
    TEL:+43 90 87 654 32 1
    END:VCARD

with the argument MaxLengthOfNames set to 20.

=head1 OPTIONS

=over 4

=item -i

The input vcard file. If not supplied, then STDIN is used as input stream.

=item -o

The output vcard file. If not supplied, then STDOUT is used as output stream.

=back

=head1 AUTHOR

Richard Bäck <richard.baeck@mailbox.org>

=cut
